## 不考虑绝对值

In [22]:
import numpy as np

name = ['apple','amazon','facebook','alibaba','baidu','xiaomi','tencent','google','bytedance']
price = [30,40,-20,-10,20,50,5,20,50] 

## 第一种

In [23]:
np.sort(price)

array([-20, -10,   5,  20,  20,  30,  40,  50,  50])

In [24]:
list(zip(price,name))

[(30, 'apple'),
 (40, 'amazon'),
 (-20, 'facebook'),
 (-10, 'alibaba'),
 (20, 'baidu'),
 (50, 'xiaomi'),
 (5, 'tencent'),
 (20, 'google'),
 (50, 'bytedance')]

In [25]:
info_dict = dict(zip(price,name)) 

In [26]:
#注意：dictionary 不能有两个相同的key
info_dict

{-20: 'facebook',
 -10: 'alibaba',
 5: 'tencent',
 20: 'google',
 30: 'apple',
 40: 'amazon',
 50: 'bytedance'}

In [27]:
top_3 = np.sort(price)
top_3 = top_3[::-1][:3]

In [28]:
name_top3 = []
for i in top_3:
    name_top3.append(info_dict[i])

In [29]:
name_top3

['bytedance', 'bytedance', 'amazon']

In [30]:
top_3

array([50, 50, 40])

## 第二种

In [31]:
info_tuple = []
for i in range(len(price)):
    info_tuple.append((name[i],price[i]))

In [32]:
list(zip(name,price))

[('apple', 30),
 ('amazon', 40),
 ('facebook', -20),
 ('alibaba', -10),
 ('baidu', 20),
 ('xiaomi', 50),
 ('tencent', 5),
 ('google', 20),
 ('bytedance', 50)]

In [33]:
info_tuple

[('apple', 30),
 ('amazon', 40),
 ('facebook', -20),
 ('alibaba', -10),
 ('baidu', 20),
 ('xiaomi', 50),
 ('tencent', 5),
 ('google', 20),
 ('bytedance', 50)]

In [34]:
sorted_list = sorted(info_tuple, key = lambda x:x[1], reverse = True)

In [35]:
sorted_list[:3]

[('xiaomi', 50), ('bytedance', 50), ('amazon', 40)]

In [36]:
sorted(info_tuple, key = lambda x: x[1],reverse=True)

[('xiaomi', 50),
 ('bytedance', 50),
 ('amazon', 40),
 ('apple', 30),
 ('baidu', 20),
 ('google', 20),
 ('tencent', 5),
 ('alibaba', -10),
 ('facebook', -20)]

## 第三种 bubule sort O(N^2)

In [37]:
def bubbleSort(arr):
    n = len(arr)
  
    # Traverse through all array elements
    for i in range(n):
        
 
        # Last i elements are already
        #  in place
        for j in range(0, n-i-1):
  
            # traverse the array from 0 to
            # n-i-1. Swap if the element 
            # found is greater than the
            # next element
            if arr[j] < arr[j+1] :
                arr[j], arr[j+1] = arr[j+1], arr[j]
               
    return arr

In [38]:
bubbleSort(price)

[50, 50, 40, 30, 20, 20, 5, -10, -20]

In [39]:
info_tuple

[('apple', 30),
 ('amazon', 40),
 ('facebook', -20),
 ('alibaba', -10),
 ('baidu', 20),
 ('xiaomi', 50),
 ('tencent', 5),
 ('google', 20),
 ('bytedance', 50)]

In [40]:
def bubbleSort_tuple(arr):
    n = len(arr)
  
    # Traverse through all array elements
    for i in range(n):
        
 
        # Last i elements are already
        #  in place
        for j in range(0, n-i-1):
  
            # traverse the array from 0 to
            # n-i-1. Swap if the element 
            # found is greater than the
            # next element
            if arr[j][1] < arr[j+1][1] :
                arr[j], arr[j+1] = arr[j+1], arr[j]
               
    return arr

In [41]:
bubbleSort_tuple(info_tuple)

[('xiaomi', 50),
 ('bytedance', 50),
 ('amazon', 40),
 ('apple', 30),
 ('baidu', 20),
 ('google', 20),
 ('tencent', 5),
 ('alibaba', -10),
 ('facebook', -20)]

## 考虑绝对值

In [221]:
name = ['apple','amazon','facebook','alibaba','baidu','xiaomi','tencent','google']
price = [30,40,-20,-10,20,50,5,20] 
price_no_sign = np.abs(price)
price_no_sign

array([30, 40, 20, 10, 20, 50,  5, 20])

In [219]:
list_info = []
for i in range(len(price_no_sign)):
    list_info.append((name[i],price_no_sign[i]))

In [220]:
list_info

[('apple', 30),
 ('amazon', 40),
 ('facebook', 20),
 ('alibaba', 10),
 ('baidu', 20),
 ('xiaomi', 50),
 ('tencent', 5),
 ('google', 20)]

In [222]:
bubbleSort_tuple(list_info)

[('xiaomi', 50),
 ('amazon', 40),
 ('apple', 30),
 ('facebook', 20),
 ('baidu', 20),
 ('google', 20),
 ('alibaba', 10),
 ('tencent', 5)]

## MergeSort     
### Big(O) = nlogn   
### Space = n

In [62]:
def merge(a,b):
    """ Function to merge two arrays """
    c = []
    while len(a) != 0 and len(b) != 0:
        if a[0] < b[0]:
            c.append(a[0])
            a.remove(a[0])
        else:
            c.append(b[0])
            b.remove(b[0])
    if len(a) == 0:
        c += b
    else:
        c += a
    return c

# Code for merge sort

def mergesort(x):
    """ Function to sort an array using merge sort algorithm """
    if len(x) == 0 or len(x) == 1:
        return x
    else:
        middle = len(x)//2
        a = mergesort(x[:middle])
        b = mergesort(x[middle:])
        return merge(a,b)

In [63]:
lst = [4,5,1,3,2,7,6]
mergesort(lst)

[1, 2, 3, 4, 5, 6, 7]

In [137]:
c = Solution()
c.mergeSort([3,2,1])

[1, 2, 3]

In [138]:
def mergesort_tuple(x):
    if len(x) == 0 or len(x) == 1:
        return x
    else:
        middle = len(x) // 2
        a = mergesort_tuple(x[:middle])
        b = mergesort_tuple(x[middle:]) 
        
        return merge_tuple(a,b)

def merge_tuple(a,b):
    c = []
    
    while len(a) != 0 and len(b) != 0:
        if a[0][1] > b[0][1]:
            c.append(a[0])
            a.remove(a[0])
        else:
            c.append(b[0])
            b.remove(b[0])
    if len(a) == 0:
        c += b
    else:
        c += a
    return c

In [139]:
def mergesort_tuple(x):
    if len(x) == 0 or len(x) == 1:
        return x
    else:
        middle = len(x) // 2
        a = mergesort_tuple(x[:middle])
        b = mergesort_tuple(x[middle:]) 
        
        return merge_tuple(a,b)

def merge_tuple(a,b):
    c = []
    
    while len(a) != 0 and len(b) != 0:
        if a[0][1] > b[0][1]:
            c.append(a[0])
            a.remove(a[0])
        else:
            c.append(b[0])
            b.remove(b[0])
    if len(a) == 0:
        c += b
    else:
        c += a
    return c

In [140]:
c = Solution()
c.mergeSort([1,2,4,3])

[1, 2, 3, 4]

In [96]:
list(zip(name,price))

[('apple', 50),
 ('amazon', 50),
 ('facebook', 40),
 ('alibaba', 30),
 ('baidu', 20),
 ('xiaomi', 20),
 ('tencent', 5),
 ('google', -10),
 ('bytedance', -20)]

In [108]:
def mergesort_tuple(x):
    if len(x) == 0 or len(x) == 1:
        return x
    else:
        middle = len(x) // 2
        a = mergesort_tuple(x[:middle])
        b = mergesort_tuple(x[middle:]) 
        
        return merge_tuple(a,b)

def merge_tuple(a,b):
    c = []
    
    while len(a) != 0 and len(b) != 0:
        if a[0][1] > b[0][1]:
            c.append(a[0])
            a.remove(a[0])
        else:
            c.append(b[0])
            b.remove(b[0])
    if len(a) == 0:
        c += b
    else:
        c += a
    return c

In [109]:
mergesort_tuple(list(zip(name,price)))

[('amazon', 50),
 ('apple', 50),
 ('facebook', 40),
 ('alibaba', 30),
 ('xiaomi', 20),
 ('baidu', 20),
 ('tencent', 5),
 ('google', -10),
 ('bytedance', -20)]

In [114]:
import numpy as np

name = ['apple','amazon','facebook','alibaba','baidu','xiaomi','tencent','google','bytedance']
price = [30,40,-20,-10,20,50,5,20,50]



#不考虑绝对值
sorted(list(zip(name,price)), key = lambda x:x[1],reverse = True)



[('xiaomi', 50),
 ('bytedance', 50),
 ('amazon', 40),
 ('apple', 30),
 ('baidu', 20),
 ('google', 20),
 ('tencent', 5),
 ('alibaba', -10),
 ('facebook', -20)]

In [115]:

#考虑绝对值
name = ['apple','amazon','facebook','alibaba','baidu','xiaomi','tencent','google','bytedance']
price = [30,40,-20,-10,20,50,5,20,50]
price_abs = np.abs(price) 


sorted(list(zip(name,price_abs)), key = lambda x:x[1],reverse = True)


[('xiaomi', 50),
 ('bytedance', 50),
 ('amazon', 40),
 ('apple', 30),
 ('facebook', 20),
 ('baidu', 20),
 ('google', 20),
 ('alibaba', 10),
 ('tencent', 5)]

In [116]:
def mergeSortTuple(x):
    if len(x) == 0 or len(x) == 1:
        return x
    else:
        middle = len(x) // 2
        a = mergeSortTuple(x[:middle])
        b = mergeSortTuple(x[middle:])
        
        return mergeTTuple(a,b)

def mergeTTuple(a,b):
    c = []
    while len(a) != 0 and len(b) != 0:
        if a[0][1] > b[0][1]:
            c.append(a[0])
            a.remove(a[0])
        else:
            c.append(b[0])
            b.remove(b[0])
    if len(a) == 0:
        c += b
    else:
        c += a
    return c

In [118]:
mergeSortTuple(list(zip(name,price)))

[('bytedance', 50),
 ('xiaomi', 50),
 ('amazon', 40),
 ('apple', 30),
 ('google', 20),
 ('baidu', 20),
 ('tencent', 5),
 ('alibaba', -10),
 ('facebook', -20)]

In [122]:
def bubbleSortTuplee(x):
    length = len(x)
    for i in range(len(x)):
        for j in range(length-i-1):
            if x[j][1] < x[j+1][1]:
                x[j] , x[j+1] =x[j+1] , x[j]
    return x

In [123]:
bubbleSortTuplee(list(zip(name,price)))

[('xiaomi', 50),
 ('bytedance', 50),
 ('amazon', 40),
 ('apple', 30),
 ('baidu', 20),
 ('google', 20),
 ('tencent', 5),
 ('alibaba', -10),
 ('facebook', -20)]

## HeapSort Topk

In [139]:
import heapq
import random
import time

def createArray():
    array = list(range( 10 * 1000 ))
    random.shuffle( array )
    return array

def linearSearch( bigArray, k ):
    return sorted(bigArray, reverse=True)[:k]

def heapSearch( bigArray, k ):
    heap = []
    # Note: below is for illustration. It can be replaced by 
    # heapq.nlargest( bigArray, k )
    for item in bigArray:
        # If we have not yet found k items, or the current item is larger than
        # the smallest item on the heap,
        if len(heap) < k or item > heap[0]:
            # If the heap is full, remove the smallest element on the heap.
            if len(heap) == k: heapq.heappop( heap )
            # add the current element as the new smallest.
            heapq.heappush( heap, item )
    return heap

start = time.time()
bigArray = createArray()
print ("Creating array took %g s" % (time.time() - start))

start = time.time()
print (linearSearch( bigArray, 3 ))    
print ("Linear search took %g s" % (time.time() - start))

start = time.time()
print (heapSearch( bigArray, 3 ))    
print ("Heap search took %g s" % (time.time() - start))

Creating array took 0.0115421 s
[9999, 9998, 9997]
Linear search took 0.00312495 s
[9997, 9998, 9999]
Heap search took 0.00123 s


In [149]:
import heapq
import random

def create_List():
    biglist = list(range(1000*1000))
    random.shuffle(biglist) 
    
    return biglist

def heapSortK(arr,k):
    heap = []
    
    for item in arr:
        if len(heap) < k or item > heap[0]:
            if len(heap) == k:
                heapq.heappop(heap)
            heapq.heappush(heap,item)
    return heap

    return heap

heapSortK(create_List(),10)

[999990,
 999992,
 999991,
 999994,
 999993,
 999995,
 999999,
 999997,
 999998,
 999996]